Fix narrowing conversions seen on 32bit arm
This issue is seen with clang-19 when compiling for arm32
make clang-19 happier with -Wc++11-narrowing

Fixes
native_skia_output_device_opengl.cpp:292:47: error: non-constant-expression cannot be narrowed from type '
   ↪ uint32_t' (aka 'unsigned int') to 'EGLAttrib' (aka 'int') in initializer list [-Wc++11-narrowing]
     292 |                 EGL_DMA_BUF_PLANE0_PITCH_EXT, nativePixmap->GetDmaBufPitch(0),

Pick-to: 6.8
Change-Id: I95ba1ab0a37218b6d05324df563efba6d5c39ba2
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
(cherry picked from commit f94d2a539c3189b086615749cfde65ca2058e04c)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 8bc191ff6e879cb01ae4f2a2fc719f5b9b3eed4e)