QWebEngineNavigationRequest: Prospective fix for clang parsers
The clang parser in Qt for Python and likely qdoc choke at
QT_DEPREQT_DEPRECATEDCATED Q_ENUM:
QtWebEngineCore/qwebenginenavigationrequest.h:85:19: error: expected member name or ';' after declaration specifiers

Properly deprecating the enum would be done by specifying
QT_DEPRECATED behind the enum keyword, but that causes deprecation
warnings for the setter and getters ( action()/setAction()). Since
they are deprecated, too, just remove the deprecation from the enumeration.

Amends 13254e7950a032ebbeb11b1cf54b850c8326fb30,

Change-Id: I3ecf9b52abc0b5a6e503097b7a1d20c69a1c5f93
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
Reviewed-by: Christian Tismer <tismer@stackless.com>
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>
(cherry picked from commit 6117b0ffb9a8dab550486dbfa362f7a398ff8f5b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>