Workaround for broken system header on rhel-8.10
In ci on rhel-8.10 system header
/usr/include/libxslt/xsltutils.h has not working
header guards, the file ends on:

}

so one #end if is missplaced, same header in
third_party/libxslt/src/libxslt/xsltutils.h looks correct.

The reason why this is incorrect on vm in ci
is unknown, however simply use bundled libxslt
in case of ci broken machine. The other workaround
would be dropping jumbo build which would not
require broken header guard.

Deals with:
error: ‘XSLT_DEBUG_INIT’ conflicts with a previous declaration

Task-number: COIN-1249
Change-Id: I94efdc14ce49cd51ff8a320765bcd55a7deb0d6f
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>