[rust] Disable rust thin-lto
When built with clang + lld + release config, use_thin_lto is enabled.
This results in the unstable/nightly flag -Zsplit-lto-unit added in
chromium/build/config/compiler/BUILD.gn unless we explicitly turn off
`toolchain_supports_rust_thin_lto`.

Fixes "FAILED: obj/build/rust/allocator/liballoc_error_handler_impl_ffi.rlib
<snip>
error: the option `Z` is only accepted on the nightly compiler"

Change-Id: Ibb686ba7e7e2bb246953198f6ac81f1be9383efb
Reviewed-by: Peter Varga <pvarga@inf.u-szeged.hu>
(cherry picked from commit 021e08d28f0cd0c7fc95b88a5d6c0675979879fe)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>