tst_certificateerror: skip the handleError test
in case we build with macOS SDK below 15 and running on macOS 15.

Task-number: QTBUG-130500
Change-Id: I8e3fe7b28565aa754609f1477a8e1c15c89860d0
Reviewed-by: Tor Arne Vestbø <tor.arne.vestbo@qt.io>
(cherry picked from commit 1c90c7ce072134a8d105c4444d6db34933ca5671)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>