Silence synqt.cpp warnings-turned-errors
Says syncqt.cpp:

  ERROR: [...]/render_widget_host_view_qt_delegate_quickwindow.h does not include QT_BEGIN_NAMESPACE

Change-Id: I4109c493bbf25a6f7c65e35e9c697f15c7f0ac3f
Reviewed-by: Michal Klocek <michal.klocek@qt.io>
(cherry picked from commit e6e66f048c873b4a972860c3072ef5a7b4b383b7)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>