Fix build of webenginewidgets/simplebrowser
Add missing include to fix
    error C2027: use of undefined type 'QDebug'
on MSVC.

Change-Id: Icc62cdf36f417f30691445ab4994b822c8e37db9
Reviewed-by: Michael Brüning <michael.bruning@qt.io>