Fix undefined reference to qCompare error
Linking against qtbase 5.9 fails with

  error: undefined reference to 'bool QTest::qCompare<QString, char [13]>([...])'

due to QCOMPARE of QString with C string literal.

Change-Id: If4f4312d21d0b1a8ce2577d5f9d3a9ac0731b3a2
Reviewed-by: Peter Varga <pvarga@inf.u-szeged.hu>