Replace NULL in gl_surface_qt.cpp
Fixes build error with MSVC:
error C2440: 'return': cannot convert from 'int' to 'scoped_refptr<gl::GLSurface>'

Change-Id: Ie24528cc98951de6863c12e1d25e3722bd20b046
Reviewed-by: Allan Sandfeld Jensen <allan.jensen@qt.io>